---
title: "Regression"
author: "Esther Hur"
date: "Las updated: `r Sys.Date()`"
output: 
  html_document: 
    highlight: pygments
    theme: cerulean
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Awesome Regression example

## Simple text

This is a simple vibariate example

Two plus two equals `r 2 + 2`, 


```{r, my_setup, echo=FALSE, message=FALSE}
2+2

library(languageR)
library(tidyverse)
data(package = "languageR")
str(spanish)
```

##Tidy some data

Here we tidy the data, 

```{r, my_plot, fig.align = 'center', fig.width=10, fig.width= 7}
my_data <- spanish %>%
  select(., x = X14461gll, y = X14473gll) %>%
  filter(., y < 0.06, x < 0.075) 

my_data  %>%
  ggplot(., aes(x= x , y = y )) +
  geom_point() +
  geom_smooth(method = 'lm')
```
## Model

Here we fit a model,

```{r, my_model}
my_fit <- lm (y ~ x, data = my_data)
summary(my_fit)
```
for calculating confidence intervals 

```{r}
confint(my_fit)
```
The data were something. (
Slope: ` r coefficients (my_fit) [2]`, CI: LB: 
`r confint(my_fit) [1, c(1, 2)]`)


```{r}
coefficients (my_fit)
```

```{r}
#test normality of residuals
hist(residuals(my_fit))
qqnorm(residuals(my_fit))
qqline(residuals(my_fit))
```


